before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  -
    id: ov-linux
    binary: ov
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: ov-other
    binary: ov
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64

archives:
  -
    id: ov-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - ov-linux
    - ov-other
    files:
      - LICENSE
      - README.md
      - ov.yaml
      - ov-less.yaml
    format: zip

nfpms:
  -
    id: ov-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - ov-linux
    homepage: https://github.com/noborus/ov
    maintainer: Noboru Saito <noborusai@gmail.com>
    description: ov is a feature rich terminal pager.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1

brews:
  -
    name: ov
    tap:
      owner: noborus
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: noborus
      email: noborusai@gmail.com
    homepage: https://github.com/noborus/ov
    description: "Feature rich terminal pager"
    test:
      system "#{bin}/ov --version"
    install:
      bin.install "ov"

source:
  enabled: true
  files:
    - vendor